; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:ATmega328P]
platform = atmelavr
board = ATmega328P

lib_deps =
  marcoschwartz/LiquidCrystal_I2C

upload_protocol = custom
upload_flags =
  -C
  $PROJECT_PACKAGES_DIR/tool-avrdude/avrdude.conf
  -p
  atmega328p
  -c
  xplainedmini
  -P
  usb

upload_command = $PROJECT_PACKAGES_DIR/tool-avrdude/avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

monitor_speed = 57600
